### PR TITLE
Extract controller details and check them against backup metadata

### PR DESCRIPTION
**Pull request by babbageclunk**
## Description of change

Added Database.ControllerInfo and implemented it for MongoDB, and then added Restorer.CheckRestorable to compare the backup file's metadata and the controller information.

## QA steps

Try to restore a backup created from a different controller, it should be rejected by the precheck.

Restoring a backup created from the same controller is allowed.

### CODE REVIEW

**Comment by babbageclunk** [comment]
The controller UUID isn't in the backup metadata at the moment. I guess I could dig it out of the controllerSettings doc in the controllers.bson file?

**Comment by babbageclunk** [comment]
You're right though, using the controller model uuid rather than the controller uuid does feel a bit like referring to the whole thing by one of its parts.

**Comment by babbageclunk** [comment]
We can add that later anyway.

$$merge$$

**Comment by babbageclunk** [comment]
Oops, missed the button!

**Comment by anastasiamac** [comment]
Oooh ... I thought I have added it to the metadata on juju/juju side? I thought it is in the new format version 1? but yes, for the older format version, we'd need to dig...

**Pull request merged**
